# Site settings
title: Siddarth Malreddy
email: 
description: ""
baseurl: ""
url: "http://malreddysid.github.io"
linkedin_username: malreddysid
github_username:  malreddysid

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
